### ISSUE TITLE
gr-fosphor: Bulid fails

### ISSUE THREAD

**Issue by ikarus23** [gnuradio/recipes#65]
Hi,
I have trouble installing gr-fosphor using pybombs. Did I miss something obvious?
My system is a Ubuntu 15.04 (64 bit). I've checked out the latest version of pybombs.

```
$ ./pybombs install gr-fosphor
Settled on prefix: /home/gnuradio/sdr/pybombs-root
Initializing environmental variables...
Loading recipes ...
/home/gnuradio/sdr/pybombs-root
Installing packages:
* gr-fosphor
Installing from source: gr-fosphor

    CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/gnuradio/sdr/pybombs-root $config_opt

Configuring: (100%) [==========================================================]
Configuration failed. Re-trying with higher verbosity.
make: *** No targets specified and no makefile found. Stop.
Build failed. See output above for error messages.
```

**Comment by ikarus23** [comment]
Using the `-v` option I figured out the OpenCL stuff is missing...

**Comment by ikarus23** [comment]
Ok, nevermind. Installing gr-fosphor in a virtualbox guest system is a stupid idea...

**Comment by ghost** [comment]
I got it working with Debian/Mint on virtualbox ( https://i.imgur.com/OaGiun2.jpg?1 ) once I learned that OpenCL can work on CPU's if you install a binary from Intel or AMD, it can work without a GPU (you will still need 3D acceleration enabled in the VM, but you will not be using it for the actual processing)
I mostly followed the instructions here (https://gist.github.com/rmcgibbo/6314452) some of the filenames were a bit out of date, but it all worked.

Goto https://software.intel.com/en-us/articles/opencl-drivers
Download the "Intel SDK for OpenCL Applications"
(In my case "wget http://registrationcenter.intel.com/irc_nas/5193/intel_code_builder_for_opencl_2015_ubuntu_5.0.0.43_x64.tgz" )
$ tar xf intel_code_builder_for_opencl_2015_ubuntu_5.0.0.43_x64.tgz
$ sudo apt-get install -y rpm alien libnuma1
Convert the rpm packages into deb packages and install them with this script.
#/bin/bash
 for f in *.rpm; do
   fakeroot alien --to-deb $f
 done
 for f in *.deb; do
   sudo dpkg -i $f
 done

$ sudo mkdir -p /etc/OpenCL/vendors/
$ sudo ln -s /opt/intel/opencl-1.2-5.0.0.43/etc/intel64.icd /etc/OpenCL/vendors/intel64.icd
$ sudo ln -s /opt/intel/opencl-1.2-5.0.0.43/lib64/libOpenCL.so.1.2 /usr/lib/libOpenCL.so
$ sudo ln -s /opt/intel/opencl-1.2-5.0.0.43/lib64/libOpenCL.so.1.2 /usr/lib/libOpenCL.so.1
$ sudo ln -s /opt/intel/opencl-1.2-5.0.0.43/lib64/libOpenCL.so.1.2 /usr/lib/libOpenCL.so.1.2
$ export OPENCL_INCLUDE_DIRS=/opt/intel/opencl-1.2-sdk-5.0.0.43/include
$ export OPENCL_ROOT_DIR=/opt/intel/opencl-1.2-sdk-5.0.0.43/
$ cd ~/pybombs
$ ./pybombs install gr-fosphor

And then you can use it as a sink in gnuradio-companion
